
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  redis:
    host: localhost
    port: 6379

logging:
  pattern:
    console: "%d{HH:mm:ss} %clr(%.-1level) %msg%n"

spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
