
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true


logging:
  pattern:
    console: "%d{HH:mm:ss} %clr(%.-1level) %msg%n"
